version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  lint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build
workflows:
  lint-and-build:
    jobs:
      - lint
      - build
